apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nova.fullname" . }}-config
  labels:
    {{- include "nova.labels" . | nindent 4 }}
data:
  nova.config.yaml: |
    {{- toYaml .Values.novaConfig | nindent 4 }}
