apiVersion: v1
kind: Namespace
metadata:
  name: nova-monitoring
  labels:
    name: nova-monitoring

---
apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    name: production

---
apiVersion: v1
kind: Namespace
metadata:
  name: db-postgres
  labels:
    name: db-postgres
