import type { DiscoverySuggestion } from "@/lib/discovery/fingerprint"

// GitOps YAML generation. Turns a discovery suggestion (or an explicit set of
// queries) into a `metrics:` fragment the operator copies into nova.config.yaml
// and commits. Nova stays file-authoritative — this AUTHORS config, it never
// writes it. Pure + dependency-free so it runs in the browser (copy/download)
// and is fully unit-testable.
//
// Output is valid YAML that round-trips through MetricsConfigSchema: PromQL
// values are emitted as single-quoted scalars (the one YAML quoting style that
// needs no escaping beyond doubling an embedded quote).

export interface GenerateMetricsYamlInput {
  /** Prometheus URL. Emitted via a ${PROMETHEUS_URL:-…} env placeholder so the
   * committed file carries no environment-specific host. */
  url?: string
  serviceLabel: string
  /** metric key → PromQL. Order is preserved as given. */
  queries: Record<string, string>
  /** Recorded as `metrics.preset` for provenance. */
  preset?: string
  /** Bearer-token ENV VAR NAME (never a value). */
  authTokenEnv?: string
}

/** YAML single-quoted scalar (double any embedded single quote). */
function yq(value: string): string {
  return `'${value.replace(/'/g, "''")}'`
}

/** Render the `metrics:` block for the given queries, ready to commit. */
export function generateMetricsYaml(input: GenerateMetricsYamlInput): string {
  const url = input.url && input.url.trim().length > 0 ? input.url : "http://prometheus:9090"
  const lines: string[] = [
    "# Generated by Nova discovery — review, then commit to nova.config.yaml.",
    "# Nova is only a PromQL client; verify the service label and status-code",
    "# label match your exporter before relying on these numbers.",
    "metrics:",
    "  provider: prometheus",
    `  url: \${PROMETHEUS_URL:-${url}}`,
    `  serviceLabel: ${input.serviceLabel}`,
  ]
  if (input.authTokenEnv) lines.push(`  authTokenEnv: ${input.authTokenEnv}`)
  if (input.preset) lines.push(`  preset: ${input.preset}`)

  const keys = Object.keys(input.queries)
  if (keys.length > 0) {
    lines.push("  queries:")
    for (const key of keys) {
      lines.push(`    ${key}: ${yq(input.queries[key])}`)
    }
  }
  return lines.join("\n") + "\n"
}

/** Convenience: build the YAML from a discovery suggestion. */
export function suggestionToYaml(
  suggestion: DiscoverySuggestion,
  opts: { url?: string; authTokenEnv?: string } = {}
): string {
  return generateMetricsYaml({
    url: opts.url,
    serviceLabel: suggestion.serviceLabel,
    queries: suggestion.queries,
    preset: suggestion.presetId,
    authTokenEnv: opts.authTokenEnv,
  })
}
